[book]
title = "Rust By Practice"
description = "Учите Rust по Примерам, Упражнениям и на Практике, написанна с ❤️ командой https://course.rs"
authors = ["sunface, https://im.dev"]
language = "ru"

[output.html.playpen]
editable = true
editor = "ace"

[output.html.fold]
enable = true
level = 1

[output.html]
additional-css = ["theme/style1.css"]
additional-js = ["assets/custom3.js", "assets/lang1.js"]
git-repository-url = "https://github.com/sunface/rust-by-practice"
edit-url-template = "https://github.com/sunface/rust-by-practice/edit/master/en/{path}"

[rust]
edition = "2021"
